Fix texts in StringsJapanese.kt
sdercolin/vlabeler pull request #19
Opened 2022-12-05 13:13 UTC by salmon-21

I have fixed typos and unnatural parts and unified the expressions.(I use deepl translation)

2022-12-05 15:39 UTC, sdercolin requested changes
Thank you! basically LGTM, please check comments.

2022-12-05 15:39 UTC, sdercolin commented on src/jvmMain/kotlin/com/sdercolin/vlabeler/ui/string/StringsJapanese.kt
> +    FilterDoneIgnored -> "完成状態でフィルターしない"
`FilterStarIgnored` and `FilterDoneIgnored` should use similar phrases for consistency

2022-12-05 15:39 UTC, sdercolin commented on src/jvmMain/kotlin/com/sdercolin/vlabeler/ui/string/StringsJapanese.kt
> +    PreferencesEditorNotes -> "メモ"
Please keep this item unchanged. `備考` is used in other documentations and texts

2022-12-05 15:39 UTC, sdercolin commented on src/jvmMain/kotlin/com/sdercolin/vlabeler/ui/string/StringsJapanese.kt
> +    PreferencesKeymapDescription -> "キーボード/マウス操作のキーマップをカスタマイズします。"
For consistency, please edit all the other `編集します` instances, or keep them unchanged.

2022-12-05 19:22 UTC, salmon-21 commented on src/jvmMain/kotlin/com/sdercolin/vlabeler/ui/string/StringsJapanese.kt
> +    PreferencesEditorNotes -> "メモ"
updated.

2022-12-05 19:23 UTC, salmon-21 commented on src/jvmMain/kotlin/com/sdercolin/vlabeler/ui/string/StringsJapanese.kt
> +    PreferencesKeymapDescription -> "キーボード/マウス操作のキーマップをカスタマイズします。"
updated.

2022-12-06 05:48 UTC, sdercolin approved these changes
LGTM!

2022-12-06 05:52 UTC, merged